FROM adoptopenjdk/openjdk11:alpine-slim
MAINTAINER openintegrationhub.org
COPY target/oihplus-web-server-0.0.1-SNAPSHOT.jar oihplus-web-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/oihplus-web-server-0.0.1-SNAPSHOT.jar"]